trigger:
  branches:
    include:
      - main  # Adjust the branch name if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk
    displayName: 'Install Java 11'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-B'  # Optional: Specify Maven command-line options
      goals: 'clean test'  # Specify the Maven goals to execute
    displayName: 'Run Maven Tests'
