trigger:
  branches:
    include:
      - main  # Adjust this to your main branch name

pool:
  vmImage: 'ubuntu-latest'  # Choose the appropriate VM image

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Path to your POM file
      options: '-Dtest=runner.MyTestrunner'  # Specify the test runner class to execute
      goals: 'test'  # Run Maven test goal
