trigger:
  branches:
    include:
      - main  # Adjust this to your main branch name

pool:
  vmImage: 'ubuntu-latest'  # Choose the appropriate VM image

steps:

  - script: |
      mvn clean test  # Assuming you are using Maven for your Java project
    displayName: 'Run Tests'
