trigger:
  branches:
    include:
      - main  # Adjust the branch name if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      architecture: 'x64'  # Adjust architecture if needed
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-B'  # Optional: Specify Maven command-line options
      goals: 'clean test'  # Specify the Maven goals to execute
