trigger:
  branches:
    include:
      - main  # Adjust the branch name if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-B'  # Optional: Specify Maven command-line options
      goals: 'clean test'  # Specify the Maven goals to execute
